package com.medibook.provider.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDate;

/*
 * This is the Provider entity — it maps directly to the providers table in MySQL.
 *
 * Think of it like this:
 * User table stores basic info — name, email, password (for ALL users)
 * Provider table stores doctor specific info — specialization, clinic, rating
 *
 * Every doctor has TWO records:
 * 1. One in users table (basic account)
 * 2. One in providers table (professional profile)
 *
 * They are linked by userId field.
 * When patient searches for a doctor — we query providers table.
 * When doctor logs in — we query users table.
 */
@Entity
@Table(name = "providers")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Provider {

    /*
     * Unique ID for every provider profile.
     * Auto generated by MySQL — we never set this manually.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int providerId;

    /*
     * Links this provider profile to the users table.
     * userId comes from User entity (UC1).
     * One user can have only one provider profile.
     */
    @Column(nullable = false, unique = true)
    private int userId;

    /*
     * Type of medical specialization.
     * Example: Cardiologist, Dermatologist, Dentist
     * Patients filter doctors by this field.
     */
    @Column(nullable = false)
    private String specialization;

    /*
     * Educational qualification of doctor.
     * Example: MBBS, MD, BDS
     * Admin checks this before verifying the doctor.
     */
    @Column(nullable = false)
    private String qualification;

    /*
     * Number of years the doctor has been practicing.
     * Shown on profile page to help patients decide.
     */
    private int experienceYears;

    /*
     * Short description about the doctor.
     * Doctor writes their own bio.
     * Shown on their profile page.
     */
    private String bio;

    /*
     * Name of clinic or hospital.
     * Example: Apollo Hospital, City Clinic
     */
    @Column(nullable = false)
    private String clinicName;

    /*
     * Full address of the clinic.
     * Patients use this to visit in person.
     */
    @Column(nullable = false)
    private String clinicAddress;

    /*
     * Average star rating given by patients.
     * Calculated automatically from all reviews.
     * Updated every time a new review is submitted.
     * Default is 0.0 when doctor first registers.
     */
    private double avgRating = 0.0;

    /*
     * Is this doctor verified by admin?
     * Default is false when doctor first registers.
     * Admin reviews qualifications and sets this to true.
     * Doctor only appears in patient search when isVerified = true.
     * This is an important business rule from the PDF.
     */
    @Column(nullable = false)
    private boolean isVerified = false;

    /*
     * Is this doctor currently available for appointments?
     * Doctor can turn this off when they are on leave.
     * Patients only see available doctors in search results.
     */
    @Column(nullable = false)
    private boolean isAvailable = true;

    /*
     * When did this doctor join MediBook?
     * Auto set when provider profile is created.
     * Used in admin analytics and reports.
     */
    @Column(nullable = false, updatable = false)
    private LocalDate createdAt;

    /*
     * Auto set the createdAt date when provider is first saved.
     * @PrePersist runs automatically before INSERT into database.
     * We never set createdAt manually — JPA handles it.
     */
    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDate.now();
    }
}
//```
//
//**Why this entity is designed this way:**
//```
//Two table design (users + providers):
//→ keeps user account separate from professional profile
//→ if doctor deactivates account → user record deleted
//  but provider history stays
//→ clean separation of concerns
//
//isVerified = false by default:
//→ doctor cannot appear in search until admin approves
//→ prevents fake doctors from joining platform
//→ this is a strict PDF requirement
//
//avgRating updated automatically:
//→ every time patient submits review
//→ ReviewService calls ProviderService.updateRating()
//→ recalculates average and updates this field